version: '3.8'

services:
  timetable-service:
    build: .
    ports:
      - "${HOST_PORT:-3000}:${PROD_PORT:-3000}"
    environment:
      - NODE_ENV=prod
      - PROD_PORT=3000
      - TEST_PORT=4000
      - LOG_LEVEL=info
      - ACCESS_TOKEN_LIFETIME=3600
      - REFRESH_TOKEN_LIFETIME=360000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-timetable}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - timetable-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-timetable}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "${DB_HOST_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - timetable-network

volumes:
  postgres_data:

networks:
  timetable-network:
    driver: bridge
