apiVersion: v1
kind: Service
metadata:
  name: timetable-service
  labels:
    app: timetable-service
spec:
  selector:
    app: timetable-service
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP